import AppKit
import Foundation

public final class PasteboardMonitor: @unchecked Sendable {
  private let pasteboard = NSPasteboard.general
  private var lastChangeCount: Int
  private var timer: DispatchSourceTimer?
  private var isConnected: Bool = false
  private var currentIntervalMs: Int = 1500
  private let queue = DispatchQueue(label: "com.prabotics.rapidrop.pasteboardmonitor", qos: .utility)

  private static let sensitiveTypeIdentifiers: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.forklabs.PasteboardType.Transient",
    "kUTTypePassword",
  ]

  public var onClipCaptured: (@Sendable (ClipItem) -> Void)?

  public init() {
    self.lastChangeCount = pasteboard.changeCount
  }

  public func setConnected(_ connected: Bool) {
    queue.async { [weak self] in
      guard let self else { return }
      guard self.isConnected != connected else { return }
      self.isConnected = connected
      let newInterval = connected ? 400 : 1500
      guard self.currentIntervalMs != newInterval else { return }
      self.currentIntervalMs = newInterval
      if let timer = self.timer {
        timer.schedule(
          deadline: .now(), repeating: .milliseconds(newInterval), leeway: .milliseconds(50))
      }
    }
  }

  public func start() {
    queue.async { [weak self] in
      guard let self else { return }
      let source = DispatchSource.makeTimerSource(queue: self.queue)
      let interval = self.isConnected ? 400 : 1500
      self.currentIntervalMs = interval
      source.schedule(
        deadline: .now(), repeating: .milliseconds(interval), leeway: .milliseconds(50))
      source.setEventHandler { [weak self] in
        self?.poll()
      }
      source.resume()
      self.timer = source
    }
  }

  public func stop() {
    queue.async { [weak self] in
      self?.timer?.cancel()
      self?.timer = nil
    }
  }

  private func poll() {
    let currentCount = pasteboard.changeCount
    guard currentCount != lastChangeCount else { return }

    lastChangeCount = currentCount

    if let item = readCurrentClip() {
      onClipCaptured?(item)
    }
  }

  public func readCurrentClip() -> ClipItem? {
    guard !hasSensitiveTypes() else { return nil }

    if let stringValue = pasteboard.string(forType: .string), !stringValue.isEmpty {
      if let url = URL(string: stringValue), url.scheme != nil, url.host != nil {
        return ClipItem(type: .url, textContent: stringValue)
      } else {
        return ClipItem(type: .text, textContent: stringValue)
      }
    }

    if let imageData = extractImageData() {
      return ClipItem(type: .image, rawData: imageData)
    }

    if let fileItem = extractFileData() {
      return fileItem
    }

    return nil
  }

  public func writeToPasteboard(item: ClipItem, savedFileURL: URL? = nil) {
    DispatchQueue.main.async { [weak self] in
      guard let self else { return }
      self.pasteboard.clearContents()

      switch item.type {
      case .text:
        if let text = item.textContent {
          self.pasteboard.setString(text, forType: .string)
        }
      case .url:
        if let urlString = item.textContent {
          self.pasteboard.setString(urlString, forType: .string)
          if let url = URL(string: urlString) {
            self.pasteboard.writeObjects([url as NSURL])
          }
        }
      case .image:
        if let data = item.rawData, let image = NSImage(data: data) {
          self.pasteboard.writeObjects([image])
        }
      case .file:
        if let targetURL = savedFileURL {
          self.pasteboard.writeObjects([targetURL as NSURL])
        } else if let data = item.rawData, let name = item.fileName {
          let tempDir = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(
            "RapiDrop")
          try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
          let safeName = URL(fileURLWithPath: name).lastPathComponent
          let filename = safeName.isEmpty ? "synced_file.bin" : safeName
          let targetURL = tempDir.appendingPathComponent(filename)
          try? data.write(to: targetURL)
          self.pasteboard.writeObjects([targetURL as NSURL])
        }
      }

      self.queue.async { [weak self] in
        guard let self else { return }
        self.lastChangeCount = self.pasteboard.changeCount
      }
    }
  }

  private func hasSensitiveTypes() -> Bool {
    guard let types = pasteboard.types else { return false }
    for type in types {
      if Self.sensitiveTypeIdentifiers.contains(type.rawValue) {
        return true
      }
    }
    return false
  }

  private func extractImageData() -> Data? {
    if let pngData = pasteboard.data(forType: .png) {
      return pngData.count <= WireFrame.maxPayloadSize ? pngData : nil
    }
    if let tiffData = pasteboard.data(forType: .tiff),
      let imageRep = NSBitmapImageRep(data: tiffData),
      let convertedPng = imageRep.representation(using: .png, properties: [:])
    {
      return convertedPng.count <= WireFrame.maxPayloadSize ? convertedPng : nil
    }
    return nil
  }
  private func extractFileData() -> ClipItem? {
    guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
      let firstURL = urls.first,
      firstURL.isFileURL
    else {
      return nil
    }

    var isDir: ObjCBool = false
    guard FileManager.default.fileExists(atPath: firstURL.path, isDirectory: &isDir),
      !isDir.boolValue
    else {
      return nil
    }

    guard let attributes = try? FileManager.default.attributesOfItem(atPath: firstURL.path),
      let fileSize = attributes[.size] as? Int,
      fileSize > 0, fileSize <= WireFrame.maxPayloadSize
    else {
      return nil
    }

    guard let data = try? Data(contentsOf: firstURL) else {
      return nil
    }

    let ext = firstURL.pathExtension.lowercased()
    let imageExtensions: Set<String> = ["png", "jpg", "jpeg", "webp", "gif", "heic", "tiff", "bmp"]
    let fileName = firstURL.lastPathComponent

    if imageExtensions.contains(ext) {
      return ClipItem(type: .image, fileName: fileName, rawData: data)
    } else {
      return ClipItem(type: .file, fileName: fileName, rawData: data)
    }
  }
}
