# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Prabotics.RapiDrop
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - RapiDrop
ReleaseDate: 2026-09-16
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Prabotics/RapiDrop/releases/download/v1.0.0/RapiDrop-Standalone-x64.exe
    InstallerSha256: 08033D810039923865DCD5EE091F9A987D744F30380F71E88FBF6351D32886E1
  - Architecture: arm64
    InstallerUrl: https://github.com/Prabotics/RapiDrop/releases/download/v1.0.0/RapiDrop-Standalone-arm64.exe
    InstallerSha256: A9ECC28363A80BCF613CD6DC8DB4B564AD24398545912B6226F5326860C74F5D
ManifestType: installer
ManifestVersion: 1.9.0
